"""empty message

Revision ID: 2b1375f344ae
Revises: 9aab99cbf5c8
Create Date: 2020-10-08 00:02:12.362090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1375f344ae'
down_revision = '9aab99cbf5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contact_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contact_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
