"""empty message

Revision ID: 48ee854eb486
Revises: 2e651eb00e3a
Create Date: 2020-10-10 18:20:06.215123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ee854eb486'
down_revision = '2e651eb00e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_address_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_contact_number_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_description_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_location_key', 'tasks', type_='unique')
    op.drop_constraint('tasks_subject_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_subject_key', 'tasks', ['subject'])
    op.create_unique_constraint('tasks_location_key', 'tasks', ['location'])
    op.create_unique_constraint('tasks_description_key', 'tasks', ['description'])
    op.create_unique_constraint('tasks_contact_number_key', 'tasks', ['contact_number'])
    op.create_unique_constraint('tasks_address_key', 'tasks', ['address'])
    # ### end Alembic commands ###
