"""empty message

Revision ID: 65291d5edd48
Revises: 7518a752d0da
Create Date: 2020-10-08 00:16:15.559915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65291d5edd48"
down_revision = "7518a752d0da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=True))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
