"""empty message

Revision ID: 96fbf8257612
Revises: cc7575091441
Create Date: 2020-10-10 23:21:09.694846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fbf8257612'
down_revision = 'cc7575091441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
